import Link from "next/link";
import { ArrowUpRight, Sparkles } from "lucide-react";
import Navbar from "@/components/landing/Navbar";
import Footer from "@/components/landing/Footer";

const principles = [
  ["Less scrolling. More showing up.", "We make finding a plan feel as quick as sending a meme in the group chat."],
  ["Your city has layers.", "The best things are often one neighbourhood, one community, or one late-night conversation away."],
  ["People over hype.", "A packed room means nothing if the people in it do not feel like your people."],
];

export default function AboutPage() {
  return <div className="min-h-screen bg-[#fafafa] text-neutral-950"><Navbar/><main><section className="mx-auto max-w-7xl px-6 py-16 lg:px-10 lg:py-28"><p className="inline-flex items-center gap-2 rounded-full border border-neutral-200 bg-white px-4 py-2 text-xs font-semibold uppercase tracking-[.18em] text-neutral-500"><Sparkles className="size-3.5"/>Built for the group chat</p><h1 className="mt-7 max-w-5xl text-[clamp(3.2rem,8vw,7rem)] font-black leading-[.88] tracking-[-.07em]">The best plans<br/>shouldn&apos;t be hard<br/>to find.</h1><p className="mt-9 max-w-xl text-lg leading-8 text-neutral-500">BunkGo is a new way to find your kind of night—small gigs, unexpected communities, low-key hangs and all the stories that start with “we almost didn&apos;t go.”</p><Link href="/discover" className="mt-9 inline-flex items-center gap-2 rounded-full bg-black px-6 py-3.5 text-sm font-semibold text-white transition hover:scale-[1.03]">Find a plan <ArrowUpRight className="size-4"/></Link></section><section className="border-y border-neutral-200 bg-white"><div className="mx-auto grid max-w-7xl gap-px px-6 md:grid-cols-3 lg:px-10">{principles.map(([title,body]) => <article key={title} className="border-neutral-200 py-10 md:border-r md:px-8 md:last:border-r-0"><p className="text-xs font-medium uppercase tracking-[.2em] text-neutral-400">Our ideology</p><h2 className="mt-5 text-2xl font-black leading-tight tracking-tight">{title}</h2><p className="mt-4 text-sm leading-6 text-neutral-500">{body}</p></article>)}</div></section><section className="mx-auto grid max-w-7xl gap-8 px-6 py-16 lg:grid-cols-[1.2fr_.8fr] lg:px-10 lg:py-24"><div className="rounded-[32px] bg-black p-8 text-white sm:p-12"><p className="text-xs font-semibold uppercase tracking-[.25em] text-neutral-500">The maker note</p><h2 className="mt-5 max-w-xl text-4xl font-black leading-[.95] tracking-[-.05em]">Made in Navi Mumbai, for people who refuse boring weekends.</h2><p className="mt-6 max-w-lg leading-7 text-neutral-400">BunkGo started with one simple belief: cities feel smaller, warmer and more alive when it is easier to walk into a room where you belong.</p></div><aside className="flex flex-col justify-between rounded-[32px] border border-neutral-200 bg-white p-8 sm:p-10"><div><p className="text-xs font-semibold uppercase tracking-[.25em] text-neutral-400">A project by</p><h2 className="mt-4 text-4xl font-black tracking-tight">Ashish<br/>Suvarna.</h2></div><p className="mt-12 text-sm leading-6 text-neutral-500">Designed to turn “kuch karna hai?” into an actual plan.</p></aside></section></main><Footer/></div>;
}
